services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - etcd_data:/etcd
    command:
      - etcd
      - --advertise-client-urls=http://127.0.0.1:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --data-dir=/etcd

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - minio_data:/minio_data
    command:
      - minio
      - server
      - /minio_data
      - --console-address=:9001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  milvus:
    image: milvusdb/milvus:v2.2.11
    container_name: milvus
    depends_on:
      - etcd
      - minio
    ports:
      - "19530:19530"  # Milvus server port
      - "19121:19121"  # Milvus management UI port
    environment:
      - TZ=UTC
      - ETCD_ENDPOINTS=etcd:2379
      - MINIO_ADDRESS=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MILVUS_MODE=standalone
    volumes:
      - milvus_data:/var/lib/milvus
    command: ["milvus", "run", "standalone"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 60s

  # JanusGraph database
  janusgraph:
    image: janusgraph/janusgraph:0.6.3
    container_name: janusgraph
    ports:
      - "8182:8182"    # Gremlin Server port
      - "8184:8184"    # JanusGraph HTTP port
      - "9160:9160"    # Cassandra Thrift port
      - "9042:9042"    # Cassandra CQL port
    environment:
      - JAVA_OPTS=-Xms512m -Xmx2g
      # Configure explicit storage backend
      - janusgraph.storage.backend=berkeleyje
      - janusgraph.storage.directory=/var/lib/janusgraph/data
    volumes:
      - janusgraph_data:/var/lib/janusgraph
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8184/status"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 60s

volumes:
  etcd_data:
  minio_data:
  milvus_data:
  janusgraph_data:

networks:
  graph_network:
    driver: bridge
